// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import RotateController from "./rotate_controller"
application.register("rotate", RotateController)

import RouletteController from "./roulette_controller"
application.register("roulette", RouletteController)
