// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RouletteController from "./roulette_controller"
application.register("roulette", RouletteController)

import StartController from "./start_controller"
application.register("start", StartController)
