AllCops:
  SuggestExtensions: false

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

plugins:
  - rubocop-performance

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'
